language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - psql -c 'create database mobileu;' -U postgres
  - echo "DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'NAME': 'mobileu', 'USER': 'postgres', 'PASSWORD': '', 'HOST': 'localhost', 'PORT': '',}}" > mobileu/production_settings.py
install:
  - "pip install -r requirements.txt --use-mirrors"
script:
  - python manage.py syncdb
  - python manage.py migrate
  - python manage.py test
