sudo: false
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch start
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-wheel"
script:
  - python manage.py syncdb
  - python manage.py migrate
  - python manage.py test
cache:
  directories:
    - $HOME/.cache/pip
