language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls"
script:
  - python manage.py syncdb
  - python manage.py migrate
  - python manage.py syncdb --all --noinput  # call AFTER migrations for permission creation
  - coverage run --source=oneplus manage.py test
after_success:
  - coveralls
